<a href="https://colab.research.google.com/github/HemantMishra2003/movie-json-parser/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

libray for numerical in python

In [32]:
arr1 = np.array([1,2,3,4])

creating 1 d array

In [33]:
arr1

array([1, 2, 3, 4])

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
arr2=np.array([[1,2,3] , [4,5,6]])

creating 2 d array

In [ ]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
type(arr2)

numpy.ndarray

In [ ]:
arr3 = np.zeros((2,3))

creating two rows and 3 colomn of array
of zeros

In [ ]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
arr4=np.ones((3,3))

In [12]:
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
arr5 = np.identity(5)

In [14]:
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
arr6 = np.arange(10)

In [16]:
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr7 =np.arange(5,15)

In [19]:
arr7

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
arr8 = np.arange(5,20,2)

In this number wil be printed out by difference of two

In [24]:
arr8

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [26]:
arr9 = np.linspace(10,20,10)

In [27]:
arr9

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [30]:
arr10 = arr9.copy()

In [31]:
arr10

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])